In [4]:
#!pip install tensorflow
import tensorflow as tf

In [5]:
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.15.0


In [8]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/ 255.0 , x_test / 255.0

In [11]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [13]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.32028297,  0.55806315, -1.0398983 ,  0.08577932,  0.22186472,
        -0.03766517,  0.81268144,  0.22620924,  0.02771069,  0.57942444]],
      dtype=float32)

In [14]:
tf.nn.softmax(predictions).numpy()

array([[0.10515251, 0.13337864, 0.02698364, 0.08317178, 0.09529653,
        0.0735131 , 0.17205432, 0.09571145, 0.07847966, 0.13625842]],
      dtype=float32)

In [15]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [16]:
loss_fn(y_train[:1], predictions).numpy()

2.6102917

In [17]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [18]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


1875/1875 [==============================] - 3s 1ms/step - loss: 0.2971 - accuracy: 0.9150
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1460 - accuracy: 0.9564
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1092 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0900 - accuracy: 0.9718
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0753 - accuracy: 0.9761


In [19]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0727 - accuracy: 0.9787 - 356ms/epoch - 1ms/step


[0.07274935394525528, 0.9786999821662903]

In [20]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [21]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.3332967e-09, 6.3078200e-09, 4.4991202e-06, 8.2734812e-05,
        6.8655684e-12, 7.0812490e-08, 6.1381623e-15, 9.9990058e-01,
        3.1577986e-08, 1.2052368e-05],
       [2.4542808e-09, 1.7946075e-03, 9.9820065e-01, 3.7116874e-06,
        2.4223982e-14, 2.6073832e-07, 5.8956039e-07, 1.6148907e-14,
        1.5056021e-07, 3.4486781e-15],
       [5.1566423e-07, 9.9926871e-01, 8.1766571e-05, 1.2208170e-05,
        2.3775963e-05, 4.4667704e-06, 9.9557685e-05, 3.6395827e-04,
        1.4323556e-04, 1.7561777e-06],
       [9.9971896e-01, 5.1362465e-09, 4.7726153e-05, 3.9272376e-08,
        9.9306117e-06, 2.2278052e-06, 8.5717380e-05, 9.6351987e-06,
        8.9038008e-07, 1.2490076e-04],
       [2.1610667e-06, 2.0492936e-09, 7.3278343e-06, 6.1866490e-09,
        9.9575090e-01, 1.4108383e-07, 1.6066895e-07, 8.3578234e-05,
        2.6029411e-06, 4.1531124e-03]], dtype=float32)>